/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChapasRouteImport } from './routes/chapas'
import { Route as OtimizacaoRouteImport } from './routes/otimizacao'
import { Route as PecasRouteImport } from './routes/pecas'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as RelatorioRouteImport } from './routes/relatorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapasRoute = ChapasRouteImport.update({
  id: '/chapas',
  path: '/chapas',
  getParentRoute: () => rootRouteImport,
} as any)
const OtimizacaoRoute = OtimizacaoRouteImport.update({
  id: '/otimizacao',
  path: '/otimizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasRoute = PecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapas': typeof ChapasRoute
  '/otimizacao': typeof OtimizacaoRoute
  '/pecas': typeof PecasRoute
  '/plano': typeof PlanoRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapas': typeof ChapasRoute
  '/otimizacao': typeof OtimizacaoRoute
  '/pecas': typeof PecasRoute
  '/plano': typeof PlanoRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapas': typeof ChapasRoute
  '/otimizacao': typeof OtimizacaoRoute
  '/pecas': typeof PecasRoute
  '/plano': typeof PlanoRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/chapas' | '/otimizacao' | '/pecas' | '/plano' | '/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chapas' | '/otimizacao' | '/pecas' | '/plano' | '/relatorio'
  id:
    | '__root__'
    | '/'
    | '/chapas'
    | '/otimizacao'
    | '/pecas'
    | '/plano'
    | '/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChapasRoute: typeof ChapasRoute
  OtimizacaoRoute: typeof OtimizacaoRoute
  PecasRoute: typeof PecasRoute
  PlanoRoute: typeof PlanoRoute
  RelatorioRoute: typeof RelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapas': {
      id: '/chapas'
      path: '/chapas'
      fullPath: '/chapas'
      preLoaderRoute: typeof ChapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otimizacao': {
      id: '/otimizacao'
      path: '/otimizacao'
      fullPath: '/otimizacao'
      preLoaderRoute: typeof OtimizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas': {
      id: '/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof PecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChapasRoute: ChapasRoute,
  OtimizacaoRoute: OtimizacaoRoute,
  PecasRoute: PecasRoute,
  PlanoRoute: PlanoRoute,
  RelatorioRoute: RelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
